INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Wolves, '13/08/11', 'A', 2.13, 3.29, 3.52);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Aston Villa, '13/08/11', 'D', 2.12, 3.28, 3.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Sunderland, '13/08/11', 'D', 1.5, 3.92, 7.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Arsenal, '13/08/11', 'D', 3.68, 3.35, 2.05);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Bolton, '13/08/11', 'A', 2.3, 3.26, 3.14);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Norwich, '13/08/11', 'D', 2.1, 3.31, 3.55);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Chelsea, '14/08/11', 'D', 5.54, 3.61, 1.66);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Man United, '14/08/11', 'A', 6.66, 4.02, 1.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Swansea, '15/08/11', 'H', 1.26, 5.47, 12.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Liverpool, '20/08/11', 'A', 2.53, 3.2, 2.86);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Blackburn, '20/08/11', 'H', 1.72, 3.49, 5.2);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, West Brom, '20/08/11', 'H', 1.29, 5.28, 10.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, QPR, '20/08/11', 'A', 1.53, 3.83, 6.89);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Newcastle, '20/08/11', 'A', 2.13, 3.27, 3.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Wigan, '20/08/11', 'D', 2.14, 3.27, 3.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Man City, '21/08/11', 'A', 4.69, 3.46, 1.8);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Stoke, '21/08/11', 'D', 2.52, 3.24, 2.82);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Fulham, '21/08/11', 'H', 2.33, 3.25, 3.11);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Tottenham, '22/08/11', 'H', 1.63, 3.72, 5.59);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Wolves, '27/08/11', 'D', 2.02, 3.3, 3.81);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Everton, '27/08/11', 'A', 3.14, 3.26, 2.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Norwich, '27/08/11', 'H', 1.2, 6.18, 14.66);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Bolton, '27/08/11', 'H', 1.41, 4.35, 8.11);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Sunderland, '27/08/11', 'D', 2.41, 3.24, 2.96);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, QPR, '27/08/11', 'H', 2.28, 3.25, 3.15);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Arsenal, '28/08/11', 'H', 1.48, 4.16, 6.95);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Fulham, '28/08/11', 'H', 2.11, 3.26, 3.55);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Man City, '28/08/11', 'A', 2.85, 3.28, 2.47);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Stoke, '28/08/11', 'A', 2.06, 3.27, 3.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Swansea, '10/09/11', 'H', 1.35, 4.66, 9.19);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Man United, '10/09/11', 'A', 7.91, 4.41, 1.42);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Aston Villa, '10/09/11', 'D', 2.04, 3.27, 3.76);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Wigan, '10/09/11', 'H', 1.17, 6.88, 16.27);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Liverpool, '10/09/11', 'H', 3.33, 3.25, 2.21);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Chelsea, '10/09/11', 'A', 5.19, 3.6, 1.69);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Tottenham, '10/09/11', 'A', 2.91, 3.29, 2.42);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Blackburn, '11/09/11', 'D', 1.67, 3.56, 5.44);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, West Brom, '11/09/11', 'A', 2.49, 3.27, 2.82);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Newcastle, '12/09/11', 'D', 2.43, 3.23, 2.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Newcastle, '17/09/11', 'D', 1.93, 3.36, 4.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Arsenal, '17/09/11', 'H', 4.27, 3.42, 1.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Norwich, '17/09/11', 'A', 1.76, 3.52, 4.77);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Wigan, '17/09/11', 'H', 1.52, 3.84, 6.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, West Brom, '17/09/11', 'H', 2.64, 3.2, 2.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, QPR, '17/09/11', 'A', 1.94, 3.38, 4.02);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Man City, '18/09/11', 'D', 6.28, 3.8, 1.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Chelsea, '18/09/11', 'H', 1.82, 3.44, 4.36);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Stoke, '18/09/11', 'H', 2.38, 3.2, 3.05);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Liverpool, '18/09/11', 'H', 2.62, 3.26, 2.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Bolton, '24/09/11', 'H', 1.44, 4.27, 7.55);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Swansea, '24/09/11', 'H', 1.2, 6.51, 13.75);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Wolves, '24/09/11', 'H', 1.38, 4.59, 8.62);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Everton, '24/09/11', 'H', 1.43, 4.32, 7.8);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Blackburn, '24/09/11', 'H', 1.85, 3.41, 4.39);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Man United, '24/09/11', 'D', 6.53, 3.94, 1.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Fulham, '24/09/11', 'D', 2.3, 3.25, 3.13);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Tottenham, '24/09/11', 'A', 3.97, 3.43, 1.93);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Aston Villa, '25/09/11', 'D', 2.31, 3.23, 3.14);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Sunderland, '26/09/11', 'H', 2.46, 3.26, 2.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Wigan, '01/10/11', 'H', 1.62, 3.71, 5.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Man City, '01/10/11', 'A', 5.99, 3.9, 1.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Liverpool, '01/10/11', 'A', 2.94, 3.22, 2.44);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Norwich, '01/10/11', 'H', 1.16, 7.16, 17.04);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, West Brom, '01/10/11', 'D', 2.23, 3.31, 3.24);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Newcastle, '01/10/11', 'A', 2.43, 3.26, 2.92);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Chelsea, '02/10/11', 'A', 6.52, 4, 1.52);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, QPR, '02/10/11', 'H', 1.97, 3.33, 3.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Stoke, '02/10/11', 'H', 2.59, 3.21, 2.76);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Arsenal, '02/10/11', 'H', 2.12, 3.4, 3.39);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Everton, '15/10/11', 'H', 1.35, 4.66, 9.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Man United, '15/10/11', 'D', 2.95, 3.25, 2.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Aston Villa, '15/10/11', 'H', 1.34, 4.83, 9.5);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Swansea, '15/10/11', 'H', 2.19, 3.28, 3.33);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Blackburn, '15/10/11', 'D', 1.85, 3.42, 4.37);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Fulham, '15/10/11', 'H', 2.14, 3.21, 3.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Bolton, '15/10/11', 'A', 2.29, 3.28, 3.12);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Sunderland, '16/10/11', 'H', 1.44, 4.28, 7.63);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Tottenham, '16/10/11', 'D', 2.9, 3.29, 2.42);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Wolves, '16/10/11', 'H', 2.01, 3.32, 3.83);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, West Brom, '22/10/11', 'A', 2, 3.29, 3.86);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Sunderland, '22/10/11', 'A', 2.21, 3.23, 3.33);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Norwich, '22/10/11', 'D', 1.29, 5.16, 10.77);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Wigan, '22/10/11', 'H', 1.58, 3.75, 6.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Swansea, '22/10/11', 'D', 1.99, 3.35, 3.81);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Stoke, '23/10/11', 'H', 1.55, 3.88, 6.33);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Tottenham, '23/10/11', 'A', 4.02, 3.5, 1.9);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Everton, '23/10/11', 'A', 2.34, 3.22, 3.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Man City, '23/10/11', 'A', 2.05, 3.35, 3.63);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Chelsea, '23/10/11', 'H', 8.84, 4.64, 1.36);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Arsenal, '29/10/11', 'A', 1.61, 3.8, 5.61);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Man United, '29/10/11', 'A', 4.57, 3.55, 1.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Wolves, '29/10/11', 'H', 1.16, 7.02, 18.49);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Blackburn, '29/10/11', 'D', 1.96, 3.42, 3.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Aston Villa, '29/10/11', 'D', 2.15, 3.27, 3.45);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Bolton, '29/10/11', 'H', 2.09, 3.32, 3.54);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Liverpool, '29/10/11', 'A', 3.77, 3.32, 2.02);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Fulham, '29/10/11', 'A', 2.91, 3.23, 2.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, QPR, '30/10/11', 'H', 1.37, 4.66, 8.56);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Newcastle, '31/10/11', 'A', 2.13, 3.25, 3.52);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, West Brom, '05/11/11', 'H', 1.41, 4.5, 7.76);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Norwich, '05/11/11', 'H', 1.82, 3.53, 4.38);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Chelsea, '05/11/11', 'A', 7.09, 4.3, 1.45);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Swansea, '05/11/11', 'D', 1.3, 5.15, 10.42);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Sunderland, '05/11/11', 'H', 1.24, 5.77, 12.84);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Everton, '05/11/11', 'H', 2.24, 3.26, 3.23);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Man City, '05/11/11', 'A', 9.29, 4.92, 1.34);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Stoke, '06/11/11', 'H', 2.36, 3.26, 3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Tottenham, '06/11/11', 'A', 3.15, 3.29, 2.27);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Wigan, '06/11/11', 'H', 1.9, 3.38, 4.2);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Wolves, '19/11/11', 'H', 1.59, 3.7, 6.08);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Newcastle, '19/11/11', 'H', 1.29, 5.22, 10.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Arsenal, '19/11/11', 'A', 5.06, 3.66, 1.69);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, QPR, '19/11/11', 'A', 1.8, 3.47, 4.56);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Fulham, '19/11/11', 'D', 2.33, 3.22, 3.11);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Man United, '19/11/11', 'A', 7.03, 4.02, 1.49);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Bolton, '19/11/11', 'H', 2, 3.35, 3.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Blackburn, '19/11/11', 'D', 2.47, 3.27, 2.84);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Liverpool, '20/11/11', 'A', 1.81, 3.47, 4.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Aston Villa, '21/11/11', 'H', 1.53, 3.98, 6.32);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Fulham, '26/11/11', 'D', 1.45, 4.19, 7.65);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Everton, '26/11/11', 'A', 3.01, 3.25, 2.37);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Wolves, '26/11/11', 'H', 1.23, 5.85, 13.01);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Newcastle, '26/11/11', 'D', 1.37, 4.55, 8.74);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, QPR, '26/11/11', 'H', 2.18, 3.33, 3.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Blackburn, '26/11/11', 'H', 1.8, 3.48, 4.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Wigan, '26/11/11', 'A', 1.68, 3.57, 5.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Tottenham, '26/11/11', 'A', 3.99, 3.49, 1.9);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Man City, '27/11/11', 'D', 2.78, 3.26, 2.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Aston Villa, '27/11/11', 'D', 2.22, 3.28, 3.25);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Man United, '03/12/11', 'A', 5.16, 3.6, 1.69);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Swansea, '03/12/11', 'H', 2.15, 3.31, 3.38);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Norwich, '03/12/11', 'H', 1.18, 6.73, 15.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Chelsea, '03/12/11', 'A', 3.56, 3.37, 2.07);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, West Brom, '03/12/11', 'D', 2.24, 3.29, 3.21);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Bolton, '03/12/11', 'H', 1.3, 5.02, 10.69);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Arsenal, '03/12/11', 'A', 6.05, 3.93, 1.56);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Stoke, '04/12/11', 'A', 1.71, 3.51, 5.18);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Sunderland, '04/12/11', 'H', 2.39, 3.26, 2.97);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Liverpool, '05/12/11', 'H', 3.37, 3.27, 2.17);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Everton, '10/12/11', 'H', 1.55, 3.89, 6.39);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Aston Villa, '10/12/11', 'A', 2.47, 3.27, 2.85);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, QPR, '10/12/11', 'H', 1.31, 4.92, 10.5);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Wolves, '10/12/11', 'H', 1.22, 5.91, 13.86);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Newcastle, '10/12/11', 'H', 2.42, 3.34, 2.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Fulham, '10/12/11', 'H', 2.59, 3.21, 2.75);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Wigan, '10/12/11', 'A', 1.66, 3.65, 5.45);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Tottenham, '11/12/11', 'H', 3.6, 3.39, 2.05);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Blackburn, '11/12/11', 'H', 1.88, 3.47, 4.19);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Man City, '12/12/11', 'H', 2.41, 3.32, 2.9);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, West Brom, '17/12/11', 'A', 2.35, 3.31, 3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Norwich, '17/12/11', 'D', 1.62, 3.71, 5.83);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Bolton, '17/12/11', 'H', 1.63, 3.68, 5.72);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Swansea, '17/12/11', 'D', 1.8, 3.49, 4.59);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Chelsea, '17/12/11', 'D', 8.73, 4.57, 1.38);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Stoke, '17/12/11', 'A', 2.49, 3.26, 2.85);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Liverpool, '18/12/11', 'A', 4.06, 3.38, 1.93);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Arsenal, '18/12/11', 'H', 1.69, 3.68, 5.07);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Man United, '18/12/11', 'A', 7.26, 4.14, 1.47);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Sunderland, '18/12/11', 'H', 1.37, 4.62, 8.73);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Bolton, '20/12/11', 'A', 2.12, 3.34, 3.49);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Norwich, '20/12/11', 'D', 2.07, 3.41, 3.58);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Arsenal, '21/12/11', 'A', 4.8, 3.57, 1.75);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Swansea, '21/12/11', 'H', 1.59, 3.69, 6.27);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Man United, '21/12/11', 'A', 5.08, 3.57, 1.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Stoke, '21/12/11', 'H', 1.23, 5.85, 13.01);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, West Brom, '21/12/11', 'A', 1.94, 3.4, 3.95);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Sunderland, '21/12/11', 'A', 2.43, 3.25, 2.92);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Liverpool, '21/12/11', 'D', 6.96, 3.9, 1.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Chelsea, '22/12/11', 'D', 2.55, 3.31, 2.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Newcastle, '26/12/11', 'A', 2.49, 3.31, 2.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Fulham, '26/12/11', 'D', 1.3, 5, 11.08);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Blackburn, '26/12/11', 'D', 1.25, 5.52, 13.17);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Wigan, '26/12/11', 'H', 1.16, 7.24, 18.27);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Aston Villa, '26/12/11', 'D', 1.91, 3.4, 4.13);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Everton, '26/12/11', 'D', 2.41, 3.24, 2.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Man City, '26/12/11', 'D', 7.41, 4.42, 1.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Wolves, '27/12/11', 'D', 1.22, 6.02, 13.56);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Tottenham, '27/12/11', 'A', 4.48, 3.62, 1.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, QPR, '27/12/11', 'D', 2.04, 3.33, 3.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Newcastle, '30/12/11', 'H', 1.54, 3.94, 6.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, QPR, '31/12/11', 'H', 1.26, 5.47, 12.33);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Wolves, '31/12/11', 'D', 2.2, 3.31, 3.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Aston Villa, '31/12/11', 'A', 1.27, 5.28, 11.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Blackburn, '31/12/11', 'A', 1.13, 7.89, 22.98);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Fulham, '31/12/11', 'D', 2.55, 3.31, 2.72);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Wigan, '31/12/11', 'D', 1.68, 3.64, 5.21);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Tottenham, '31/12/11', 'D', 5.14, 3.64, 1.69);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Man City, '01/01/12', 'H', 6.38, 3.98, 1.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Everton, '01/01/12', 'A', 2.58, 3.25, 2.75);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Swansea, '02/01/12', 'A', 1.82, 3.39, 4.6);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Stoke, '02/01/12', 'A', 2.49, 3.27, 2.82);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Arsenal, '02/01/12', 'H', 3.94, 3.41, 1.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Norwich, '02/01/12', 'A', 2.1, 3.32, 3.47);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Chelsea, '02/01/12', 'A', 6.31, 3.87, 1.55);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Liverpool, '03/01/12', 'H', 1.89, 3.4, 4.32);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, West Brom, '03/01/12', 'H', 1.35, 4.84, 9.26);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Sunderland, '03/01/12', 'A', 2.63, 3.23, 2.73);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Bolton, '04/01/12', 'A', 1.51, 3.99, 6.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Man United, '04/01/12', 'H', 5.05, 3.55, 1.72);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Everton, '11/01/12', 'H', 1.55, 3.83, 6.41);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Everton, '14/01/12', 'D', 2.4, 3.24, 2.99);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Fulham, '14/01/12', 'H', 2.87, 3.27, 2.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Sunderland, '14/01/12', 'H', 1.39, 4.58, 8.36);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Stoke, '14/01/12', 'D', 1.42, 4.28, 8.06);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Bolton, '14/01/12', 'H', 1.16, 7.46, 16.99);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Wolves, '14/01/12', 'D', 1.27, 5.49, 10.91);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Norwich, '14/01/12', 'A', 2.07, 3.33, 3.61);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, QPR, '15/01/12', 'H', 1.75, 3.54, 4.81);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Arsenal, '15/01/12', 'H', 4.72, 3.51, 1.77);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Man City, '16/01/12', 'A', 8.59, 4.39, 1.4);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Liverpool, '21/01/12', 'H', 5.87, 3.7, 1.62);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Blackburn, '21/01/12', 'D', 1.55, 3.8, 6.62);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Newcastle, '21/01/12', 'H', 2, 3.36, 3.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Chelsea, '21/01/12', 'D', 5.66, 3.84, 1.6);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Wigan, '21/01/12', 'H', 2.04, 3.3, 3.73);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, West Brom, '21/01/12', 'A', 1.93, 3.4, 4.02);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Swansea, '21/01/12', 'H', 1.87, 3.35, 4.37);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Aston Villa, '21/01/12', 'A', 2.51, 3.24, 2.82);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Man United, '22/01/12', 'A', 2.81, 3.29, 2.51);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Tottenham, '22/01/12', 'H', 1.88, 3.53, 4.13);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Man City, '31/01/12', 'H', 4.49, 3.49, 1.82);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Stoke, '31/01/12', 'H', 1.31, 5.15, 10.32);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Chelsea, '31/01/12', 'D', 4.14, 3.29, 1.96);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Wigan, '31/01/12', 'H', 1.22, 6.12, 14.22);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Liverpool, '31/01/12', 'A', 5.16, 3.66, 1.7);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, QPR, '01/02/12', 'D', 1.79, 3.46, 4.65);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Newcastle, '01/02/12', 'A', 2.59, 3.29, 2.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Arsenal, '01/02/12', 'D', 5.13, 3.7, 1.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, West Brom, '01/02/12', 'D', 1.83, 3.45, 4.45);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Norwich, '01/02/12', 'H', 1.85, 3.43, 4.35);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Blackburn, '04/02/12', 'H', 1.28, 5.33, 10.95);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Fulham, '04/02/12', 'H', 1.29, 5.23, 10.84);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Bolton, '04/02/12', 'H', 2.02, 3.39, 3.63);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Wolves, '04/02/12', 'A', 1.9, 3.49, 4.02);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Sunderland, '04/02/12', 'A', 2.19, 3.26, 3.35);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Swansea, '04/02/12', 'A', 2.1, 3.29, 3.54);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Everton, '04/02/12', 'D', 3.45, 3.28, 2.13);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Man United, '05/02/12', 'D', 2.51, 3.24, 2.84);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Aston Villa, '05/02/12', 'H', 2.09, 3.31, 3.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Tottenham, '06/02/12', 'D', 2.09, 3.33, 3.54);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, QPR, '11/02/12', 'H', 2.34, 3.28, 3.04);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Wigan, '11/02/12', 'A', 2, 3.43, 3.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Chelsea, '11/02/12', 'H', 3.26, 3.26, 2.24);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Stoke, '11/02/12', 'H', 1.97, 3.34, 3.92);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Liverpool, '11/02/12', 'H', 1.85, 3.49, 4.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Arsenal, '11/02/12', 'A', 3.52, 3.37, 2.08);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Norwich, '11/02/12', 'A', 1.85, 3.48, 4.3);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Newcastle, '11/02/12', 'H', 1.46, 4.22, 7.21);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Man City, '12/02/12', 'A', 5.27, 3.65, 1.68);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, West Brom, '12/02/12', 'A', 2.43, 3.24, 2.95);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Bolton, '25/02/12', 'H', 1.28, 5.39, 10.66);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Blackburn, '25/02/12', 'H', 1.17, 6.9, 16.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Wolves, '25/02/12', 'D', 1.59, 3.83, 5.9);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Fulham, '25/02/12', 'A', 2.59, 3.25, 2.72);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Sunderland, '25/02/12', 'H', 2.4, 3.26, 2.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Aston Villa, '25/02/12', 'D', 2.74, 3.25, 2.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Tottenham, '26/02/12', 'H', 2.46, 3.36, 2.8);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Man United, '26/02/12', 'A', 6.14, 4.08, 1.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Swansea, '26/02/12', 'H', 2.11, 3.28, 3.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Aston Villa, '03/03/12', 'D', 2.37, 3.3, 2.96);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Arsenal, '03/03/12', 'A', 2, 3.41, 3.74);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Bolton, '03/03/12', 'H', 1.13, 7.96, 21.06);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Everton, '03/03/12', 'D', 3.05, 3.26, 2.35);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Norwich, '03/03/12', 'H', 1.86, 3.44, 4.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Chelsea, '03/03/12', 'H', 4.02, 3.42, 1.93);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Swansea, '03/03/12', 'A', 2.44, 3.25, 2.89);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Wolves, '04/03/12', 'H', 1.58, 3.79, 6.08);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Sunderland, '04/03/12', 'D', 2.09, 3.31, 3.54);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Man United, '04/03/12', 'A', 2.86, 3.32, 2.44);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Fulham, '10/03/12', 'H', 2.46, 3.24, 2.88);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, QPR, '10/03/12', 'H', 2.41, 3.27, 2.94);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Stoke, '10/03/12', 'H', 1.39, 4.44, 8.47);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Tottenham, '10/03/12', 'H', 2.84, 3.27, 2.48);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Liverpool, '10/03/12', 'H', 3.87, 3.34, 1.98);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Blackburn, '10/03/12', 'A', 2.32, 3.31, 3.02);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, West Brom, '11/03/12', 'H', 1.28, 5.4, 10.67);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Wigan, '11/03/12', 'D', 1.84, 3.47, 4.25);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Man City, '11/03/12', 'H', 6.28, 3.7, 1.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Newcastle, '12/03/12', 'H', 1.47, 4.14, 6.98);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Everton, '13/03/12', 'H', 1.74, 3.5, 5.11);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Swansea, '17/03/12', 'A', 1.84, 3.42, 4.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, West Brom, '17/03/12', 'D', 2.75, 3.28, 2.55);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Norwich, '18/03/12', 'H', 1.78, 3.65, 4.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Man United, '18/03/12', 'A', 8.83, 4.89, 1.34);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Sunderland, '20/03/12', 'H', 2.36, 3.33, 2.98);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Arsenal, '21/03/12', 'A', 3.03, 3.29, 2.34);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Chelsea, '21/03/12', 'H', 1.89, 3.48, 4.13);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Liverpool, '21/03/12', 'H', 4.59, 3.52, 1.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Stoke, '21/03/12', 'D', 1.41, 4.33, 8.15);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Aston Villa, '24/03/12', 'H', 1.35, 4.76, 9.41);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Blackburn, '24/03/12', 'H', 2.4, 3.34, 2.91);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Tottenham, '24/03/12', 'D', 1.88, 3.49, 4.14);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Wigan, '24/03/12', 'A', 1.29, 5.16, 11.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Wolves, '24/03/12', 'H', 1.75, 3.6, 4.67);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Man City, '24/03/12', 'D', 5.91, 3.67, 1.62);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, QPR, '24/03/12', 'H', 2.01, 3.33, 3.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Everton, '24/03/12', 'A', 2.18, 3.25, 3.39);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Newcastle, '25/03/12', 'A', 2.29, 3.3, 3.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Fulham, '26/03/12', 'H', 1.24, 5.62, 13.1);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Chelsea, '31/03/12', 'A', 4.49, 3.46, 1.83);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, West Brom, '31/03/12', 'H', 1.82, 3.48, 4.48);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Norwich, '31/03/12', 'H', 1.7, 3.65, 5.05);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Sunderland, '31/03/12', 'D', 1.22, 5.95, 13.95);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Arsenal, '31/03/12', 'H', 5.62, 3.88, 1.6);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Stoke, '31/03/12', 'H', 2.6, 3.22, 2.74);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Bolton, '31/03/12', 'A', 2.31, 3.35, 3.03);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Liverpool, '01/04/12', 'H', 2.95, 3.35, 2.37);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Swansea, '01/04/12', 'H', 1.4, 4.39, 8.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Man United, '02/04/12', 'A', 8.56, 4.53, 1.38);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Newcastle, '06/04/12', 'A', 2.37, 3.31, 2.96);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Fulham, '07/04/12', 'A', 2.57, 3.3, 2.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Wigan, '07/04/12', 'H', 1.27, 5.42, 11.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Aston Villa, '07/04/12', 'D', 1.44, 4.26, 7.78);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Everton, '07/04/12', 'D', 2.9, 3.27, 2.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Wolves, '07/04/12', 'H', 1.61, 3.77, 5.74);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Tottenham, '07/04/12', 'D', 3.26, 3.38, 2.19);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Blackburn, '07/04/12', 'H', 1.95, 3.44, 3.89);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Man City, '08/04/12', 'H', 2.47, 3.36, 2.81);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, QPR, '08/04/12', 'H', 1.17, 7.01, 15.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Stoke, '09/04/12', 'D', 2.21, 3.25, 3.38);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Sunderland, '09/04/12', 'H', 1.94, 3.38, 4.04);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Chelsea, '09/04/12', 'D', 3.46, 3.33, 2.15);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Bolton, '09/04/12', 'H', 1.57, 4.02, 5.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Norwich, '09/04/12', 'A', 1.31, 5.27, 9.84);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Liverpool, '10/04/12', 'A', 3.49, 3.37, 2.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, West Brom, '11/04/12', 'H', 1.24, 5.75, 12.17);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Swansea, '11/04/12', 'H', 2.13, 3.31, 3.42);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Man United, '11/04/12', 'H', 8.85, 4.7, 1.36);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Arsenal, '11/04/12', 'A', 6.73, 4.37, 1.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Man City, '14/04/12', 'A', 6.18, 4.06, 1.53);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Wolves, '14/04/12', 'D', 1.5, 4.14, 6.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Blackburn, '14/04/12', 'H', 1.99, 3.42, 3.8);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, QPR, '14/04/12', 'H', 2.12, 3.33, 3.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Aston Villa, '15/04/12', 'H', 1.22, 6.01, 13.57);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Wigan, '16/04/12', 'A', 1.26, 5.62, 11.32);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Chelsea, '21/04/12', 'D', 1.99, 3.48, 3.7);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Sunderland, '21/04/12', 'D', 2.32, 3.27, 3.09);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Norwich, '21/04/12', 'H', 2.07, 3.43, 3.5);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Swansea, '21/04/12', 'D', 2.18, 3.32, 3.35);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Wigan, '21/04/12', 'H', 1.87, 3.49, 4.2);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Stoke, '21/04/12', 'H', 1.68, 3.63, 5.32);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Tottenham, '21/04/12', 'H', 3.97, 3.51, 1.92);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, West Brom, '22/04/12', 'A', 1.43, 4.4, 7.52);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Everton, '22/04/12', 'D', 1.31, 5.1, 9.85);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Man City, '22/04/12', 'A', 11.78, 6.1, 1.23);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Bolton, '24/04/12', 'A', 1.95, 3.45, 3.93);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Fulham, '28/04/12', 'H', 1.83, 3.46, 4.4);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Liverpool, '28/04/12', 'A', 3.7, 3.45, 1.99);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Arsenal, '28/04/12', 'D', 4.23, 3.48, 1.86);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Bolton, '28/04/12', 'D', 1.95, 3.42, 3.87);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Wolves, '28/04/12', 'D', 1.54, 3.95, 6.24);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Aston Villa, '28/04/12', 'D', 2.11, 3.34, 3.46);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Newcastle, '28/04/12', 'H', 2.78, 3.33, 2.49);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, QPR, '29/04/12', 'H', 1.39, 4.59, 8.07);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Blackburn, '29/04/12', 'H', 1.38, 4.73, 7.85);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, Man United, '30/04/12', 'H', 2.14, 3.39, 3.36);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Fulham, '01/05/12', 'A', 1.6, 3.88, 5.83);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Everton, '01/05/12', 'D', 2.95, 3.25, 2.45);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, Tottenham, '02/05/12', 'A', 3.92, 3.51, 1.93);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Newcastle, '02/05/12', 'A', 1.5, 4.18, 6.41);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Arsenal, Norwich, '05/05/12', 'D', 1.21, 6.22, 13.29);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Aston Villa, Tottenham, '06/05/12', 'D', 4.08, 3.54, 1.86);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Bolton, West Brom, '06/05/12', 'D', 2, 3.44, 3.65);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Fulham, Sunderland, '06/05/12', 'H', 1.86, 3.48, 4.17);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man United, Swansea, '06/05/12', 'H', 1.17, 6.84, 15.06);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Newcastle, Man City, '06/05/12', 'A', 4.82, 3.93, 1.66);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, QPR, Stoke, '06/05/12', 'H', 1.85, 3.52, 4.15);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wolves, Everton, '06/05/12', 'D', 4.8, 3.71, 1.71);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Blackburn, Wigan, '07/05/12', 'A', 2.44, 3.35, 2.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Liverpool, Chelsea, '08/05/12', 'H', 2.15, 3.46, 3.33);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Chelsea, Blackburn, '13/05/12', 'H', 1.3, 5.36, 9.52);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Everton, Newcastle, '13/05/12', 'H', 2.19, 3.45, 3.18);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Man City, QPR, '13/05/12', 'H', 1.13, 8.54, 18.12);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Norwich, Aston Villa, '13/05/12', 'H', 2.18, 3.38, 3.25);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Stoke, Bolton, '13/05/12', 'D', 2.41, 3.47, 2.79);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Sunderland, Man United, '13/05/12', 'A', 7.23, 4.51, 1.43);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Swansea, Liverpool, '13/05/12', 'H', 3.38, 3.45, 2.1);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Tottenham, Fulham, '13/05/12', 'H', 1.4, 4.55, 8.04);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, West Brom, Arsenal, '13/05/12', 'A', 5.02, 3.93, 1.65);
INSERT INTO matches (championship, home, away, match_date, win, home_odd, away_odd, draw_odd) VALUES (1, Wigan, Wolves, '13/05/12', 'H', 1.57, 3.95, 5.8);

