INSERT INTO teams (name, country) VALUES ('Arsenal', 'England');
INSERT INTO teams (name, country) VALUES ('Aston Villa', 'England');
INSERT INTO teams (name, country) VALUES ('Blackburn', 'England');
INSERT INTO teams (name, country) VALUES ('Bolton', 'England');
INSERT INTO teams (name, country) VALUES ('Chelsea', 'England');
INSERT INTO teams (name, country) VALUES ('Everton', 'England');
INSERT INTO teams (name, country) VALUES ('Fulham', 'England');
INSERT INTO teams (name, country) VALUES ('Liverpool', 'England');
INSERT INTO teams (name, country) VALUES ('Man City', 'England');
INSERT INTO teams (name, country) VALUES ('Man United', 'England');
INSERT INTO teams (name, country) VALUES ('Newcastle', 'England');
INSERT INTO teams (name, country) VALUES ('Norwich', 'England');
INSERT INTO teams (name, country) VALUES ('QPR', 'England');
INSERT INTO teams (name, country) VALUES ('Stoke', 'England');
INSERT INTO teams (name, country) VALUES ('Sunderland', 'England');
INSERT INTO teams (name, country) VALUES ('Swansea', 'England');
INSERT INTO teams (name, country) VALUES ('Tottenham', 'England');
INSERT INTO teams (name, country) VALUES ('West Brom', 'England');
INSERT INTO teams (name, country) VALUES ('Wigan', 'England');
INSERT INTO teams (name, country) VALUES ('Wolves', 'England');
INSERT INTO teams (name, country) VALUES ('Reading', 'England');
INSERT INTO teams (name, country) VALUES ('Southampton', 'England');
INSERT INTO teams (name, country) VALUES ('West Ham', 'England');
INSERT INTO teams (name, country) VALUES ('Cardiff', 'England');
INSERT INTO teams (name, country) VALUES ('Hull', 'England');
INSERT INTO teams (name, country) VALUES ('Crystal Palace', 'England');
